import {StyleSheet} from 'react-native';

import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

export const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: Colors.lighter,
  },
  appWrapper: {
    backgroundColor: '#ebf1fa',
    minHeight: '100%',
  },
  allowedWrapper: {
    padding: 10,
    fontSize: 20,
    borderTopWidth: 1,
  },
  allowedHeader: {
    fontSize: 24,
    marginBottom: 10,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  allowedButtons: {
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  chordAllowed: {
    backgroundColor: 'black',
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 50,
    height: 75,
    width: 75,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chordAllowedText: {
    color: 'white',
    fontSize: 24,
  },
  chordUnallowed: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 50,
    height: 75,
    width: 75,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chordUnallowedText: {
    color: 'black',
    fontSize: 24,
  },
  disabledOneChord: {
    backgroundColor: '#707070',
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 50,
    height: 75,
    width: 75,
    justifyContent: 'center',
    alignItems: 'center',
  },
  disabledOneChordText: {
    color: '#e8e8e8',
    fontSize: 24,
  },
  backButton: {
    backgroundColor: 'white',
    borderBottomWidth: 2,
    minWidth: '100%',
    marginBottom: 10,
    flexDirection: 'row',
    paddingTop: 7,
    paddingBottom: 7,
    paddingLeft: 16,
    alignContent: 'center',
  },
  backButtonText: {
    fontSize: 26,
    marginLeft: 14,
  },
  buttonRow: {
    flexDirection: 'row',
    marginLeft: 4,
    marginRight: 7,
    marginBottom: 12,
  },
  settingsSlider: {

  },
  settingsSliderView: {
    marginLeft: 0,
    marginTop: 3,
    marginBottom: 3,
    paddingTop: 7,
    paddingBottom: 7,
    flexDirection: 'row',
    borderBottomWidth: 1,
    paddingLeft: 8,
  },
  checkboxWrapper: {
    flexDirection: 'row',
    fontSize: 20,
    margin: 3,
  },
  chordCheckbox: {
    fontSize: 40,
  },
  chordCheckboxText: {
    marginLeft: 15,
    fontSize: 20,
  },
  chordButtonContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    height: 50,
    marginRight: 8,
    elevation: 3,
  },
  chordUnanswered: {
    backgroundColor: 'skyblue',
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    minWidth: '100%',
    borderWidth: 1,
    borderRadius: 5,
  },
  chordCorrect: {
    backgroundColor: 'green',
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    width: '100%',
    borderWidth: 1,
    borderRadius: 5,
  },
  chordIncorrect: {
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    minWidth: '100%',
    borderWidth: 1,
    borderRadius: 5,
  },
  chordButtonLabel: {
    textAlign: 'center',
    fontSize: 22,
  },
  chordRow1: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  chordRow2: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  chordRow3: {
    flexDirection: 'row',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginBottom: 5,
  },
  dropdown: {
    transform: [
     {scaleX: 1.2},
     {scaleY: 1.2},
   ],
   left: 7,
  },
  dropdownWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
    marginBottom: 10,
  },
  dropdownHeader: {
    fontSize: 22,
    marginBottom: 5,
    marginRight: 'auto',
  },
  explanationWrapper: {
    marginLeft: 10,
    marginRight: 10,
    marginTop: 12,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: 'white',
    padding: 7,
  },
  explanationHeaderWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    marginBottom: 10,
  },
  explanationHeader: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 20,
    marginBottom: 2,
  },
  pageNavigationButtons: {
    marginBottom: 4,
  },
  explanationIntroText: {
    fontSize: 18,
    marginBottom: 8,
    marginLeft: 12,
    marginRight: 12,
  },
  explanationText: {
    fontSize: 18,
    marginBottom: 8,
    marginLeft: 12,
    marginRight: 12,
  },
  exampleGrid: {
    marginLeft: 0,
    marginRight: 0,
    marginTop: 8,
    marginBottom: 12,
    borderWidth: 1,
    paddingTop: 6,
    paddingLeft: 1,
    paddingRight: 1,
  },
  exampleGridText: {
    fontSize: 13,
    marginBottom: 6,
  },
  exampleRowGrid: {
    flexDirection: 'row',
  },
  exampleRowTitle: {
    flex: 3,
    alignItems: 'center',
  },
  exampleRowTitleText: {
    marginLeft: 'auto',
  },
  exampleViewGrid: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  engine: {
    position: 'absolute',
    right: 0,
  },
  homeWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  body: {
    backgroundColor: Colors.white,
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  firstSettingsSlider: {
    borderTopWidth: 1,
  },
  navigationButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    marginBottom: 50,
    marginLeft: 'auto',
    marginRight: 'auto',
    width: 270,
    height: 70,
    borderWidth: 1,
    borderRadius: 10,
    elevation: 7,
  },
  navigationText: {
    textAlign: 'center',
    fontSize: 28,
  },
  pickerWrapper: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderRadius: 5,
    minWidth: 125,
    height: 50,
    marginRight: 'auto',
  },
  possibleChordsWrapper: {
    marginTop: 0,
    marginLeft: 'auto',
    marginBottom: 12,
    marginRight: 'auto',
    paddingTop: 4,
    paddingBottom: 9,
    width: 360,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: 'white',
  },
  possibleChordsHeader: {
    fontSize: 20,
    textAlign: 'center',
  },
  possibleChordsNameWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 'auto',
  },
  possibleChordsName: {
    textAlign: 'center',
    marginLeft: 8,
    fontSize: 20,
  },
  quizUIWrapper: {
    marginTop: 0,
    minHeight: 350,
  },
  rowBullet: {
    alignSelf: 'center',
    marginRight: 3,
    fontSize: 9,
    color: '#3d3d3d'
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: Colors.black,
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
    color: Colors.dark,
  },
  settingsText: {
    fontSize: 20,
  },
  settingsDropdown: {
    marginBottom: 10,
    justifyContent: 'center',
    textAlign: 'center',
  },
  settingsWrapper: {
    marginBottom: 15,
  },
  soundButton: {
    backgroundColor: 'white',
    color: 'black',
    borderWidth: 1,
    borderRadius: 5,
    height: 40,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
    margin: 4,
    elevation: 7,
  },
  soundButtonText: {
    textAlign: 'center',
  },
  soundButtonWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
    margin: 15,
  },
  titleWrapper: {
    flexDirection: 'row',
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    padding: 5,
    backgroundColor: 'white',
    borderBottomWidth: 2,
    justifyContent: 'center',
  },
  titleHeader: {
    fontSize: 23,
    fontFamily: 'serif',
    color: 'black',
    marginTop: 3,
    marginBottom: 7,
    textAlign: 'center',
    alignSelf: 'center',
  },
  homeButton: {
    backgroundColor: 'white',
    marginLeft: 4,
    alignSelf: 'center',
  },
  highlight: {
    fontWeight: '700',
  },
  footer: {
    color: Colors.dark,
    fontSize: 12,
    fontWeight: '600',
    padding: 4,
    paddingRight: 12,
    textAlign: 'right',
  },
});
